### ISSUE TITLE
Write a better Readme

### ISSUE THREAD

**Issue by Slluxx** [Da0ne/DZMods#113]
Could you please write a better readme? Its confusing af to read through this. Its unclear what to use from where, where to put stuff and what the players need to have to play. 

It would be even better to just add RPCFramework  [as a dependencie in git](https://stackoverflow.com/questions/7813030/how-can-i-have-linked-dependencies-in-a-git-repo) and set up this git repo to just make it a simple drag-n-drop overwrite of the existing files.

Do clients have to subscribe to both RPCF and DZM on the steam workshop? In my opinion it would be better to just stick to no dependencies at all for the clients.

**Comment by GravityWolfNotAmused** [comment]
> Do clients have to subscribe to both RPCF and DZM on the steam workshop? In my opinion it would be better to just stick to no dependencies at all for the clients.

Yes, clients need both RPCF, and DZM from the workshop. This should be obvious due to major of all mods being pushed to the workshop are client. It because the client doesn't need the server side code. Client's should all be directed to only use the workshop.

> It would be even better to just add RPCFramework as a dependencie in git and set up this git repo to just make it a simple drag-n-drop overwrite of the existing files.

Simple, it's not our mod and we do not have permission to package the mod together. Also, reminder if we package the mod with RPCF we will cause errors if another mod on a server also implements the same classes as RPCF, or another mod who also packages it with RPCF. Da0ne and I have talked about packaging the mod with it, but it's makes things worse for the modding community. Introducing newer and easier frameworks for DayZ will allow for add-on files to be smaller by reusing the same framework across multiple add-ons.

> Could you please write a better readme? Its confusing af to read through this. Its unclear what to use from where, where to put stuff and what the players need to have to play.

Clients should only be getting add-ons from the workshop, once again, this shouldn't be any different from every game that uses the steam workshop, and has server utilities. Players need both add-ons.

![image](https://user-images.githubusercontent.com/24533882/49422497-18385200-f762-11e8-8a67-02f6d08a1a2f.png)

**Comment by GravityWolfNotAmused** [comment]
Or are there other things that are not clear to you?

**Comment by Slluxx** [comment]
> Simple, it's not our mod and we do not have permission to package the mod together.

Thats why you add it as a dependencie to your git repo. Its like a symlink and will get added to the master.zip on download. You are not putting his project files into yours and he is still in full control.
You should read what that is about.

> Clients should only be getting add-ons from the workshop, once again, this shouldn't be any different > from every game that uses the steam workshop, and has server utilities. Players need both add-ons.

This doesn't make it easier. The readme was garbage and im glad it got changed but especialy step 1.2 is triggering me. "name the folder anything you desire, but not NewFolder". that does not explain at all what the folder is for. is it a backup? is it a folder to save new files for the new map?  

Just let the people name the folder "DayZSurvival_files" and you just got rid of a few sources of error.
